# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benoit SEvens
email: benoit.sevens@gmx.com
description: > # this means to ignore newlines until "baseurl:"
  A blog dedicated to security stuff.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://b3n7s.github.io" # the base hostname & protocol for your site
twitter_username: b3n01t
github_username:  b3n7s

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker
